### ISSUE TITLE
Requisito da disciplina satélite "Desenvolvimento Web 3"

### ISSUE THREAD

**Issue by orlandosaraivajr** [wkauan/GreenTrade#1]
O grupo definiu como escopo o "Criar um site educativo que visa despertar o interesse dos alunos por uma alimentação saudável e, ao mesmo tempo, incentivar sua frequência escolar, ao fornecer informações detalhadas sobre as refeições escolares, incluindo seus componentes nutricionais e os impactos positivos que essas refeições têm na saúde dos alunos.".

Como requisito da disciplina satélite Engenharia de software 3, o grupo deve desenvolver uma aplicação web com uso de um framework a escolha do grupo. Além disso, o grupo deve criar testes unitários, para validar partes do código de forma automática.

O framework Django, com uso de testes unitários foi amplamente explicado em sala de aula. Entretanto, o grupo tem liberdade técnica em escolher outro framework, alinhado aos requisitos explicitados e atento aos requisitos solicitados pelos demais docentes .

**Comment by orlandosaraivajr** [comment]
Em uma visita ao projeto, fiquei preocupado.
Nenhuma atualização foi feita nas últimas duas semanas. Está tudo bem com o grupo ?

![image](https://github.com/wkauan/GreenTrade/assets/2480421/21d29b69-60d8-4c2a-ab61-8afb3e97bc6d)

**Comment by wkauan** [comment]
boa tarde Orlando, desculpe não responder só vi agora. Está tudo certo com o grupo sim, apenas demoramos a começar a postar no github devido a priorizar a criação de rascunhos para o projeto

**Comment by wkauan** [comment]
> Em uma visita ao projeto, fiquei preocupado. Nenhuma atualização foi feita nas últimas duas semanas. Está tudo bem com o grupo ?
> 
> ![image](https://user-images.githubusercontent.com/2480421/280867252-21d29b69-60d8-4c2a-ab61-8afb3e97bc6d.png)


boa tarde Orlando, desculpe não responder só vi agora. Está tudo certo com o grupo sim, apenas demoramos a começar a postar no github devido a priorizar a criação de rascunhos para o projeto
